### ISSUE TITLE
Fix contact form field style

### ISSUE THREAD

**Issue by manniL** [Developmint/developmint.de#4]
Information:
* **Model:** iPhone 6S
* **Resolution:** 375 x 667
* **Reproducable through browser (FF/Chrome)?** *No*

!![IMG](https://user-images.githubusercontent.com/1947344/37630535-12af31e0-2c20-11e8-81ee-8c48452602e1.png)

Related / First time seen: https://github.com/nuxt-community/awesome-nuxt/pull/95#issuecomment-374439995

**Comment by limichange** [comment]
It's break, because of the '-', you should set a width on it.
```html
<label for="email" class="text-developmint-darker" style="width: 50px;">E-Mail</label>
```

**Comment by manniL** [comment]
@limichange Thanks for your help! I solved it with `white-space: nowrap`. :relaxed:
